name: piment
version: 0.0.3
architectures: [armhf]
summary: Reads data from SDS011 PM sensor and writes it into InfluxDB
description: |
  Installs local InfluxDB in which it writes data recieved from serial PM sensor
  and syncs it to a remote InfluxDB instance every 90 min. It also propagates influx-setup
  local InfluxDB installation via mDNS/bonjour.
grade: devel
confinement: devmode

apps:
  influx:
    command: usr/bin/influx
    plugs:
      - network
  influxd:
    command: bin/influxd.wrapper
    daemon: simple
    plugs:
      - network-bind
  exportd:
    command: bin/data-exportd.wrapper
    daemon: simple
    plugs:
      - network
  export:
    command: bin/data-export.wrapper
    plugs:
      - network
  writer:
    command: bin/db-writer.wrapper
    daemon: simple
    plugs:
      - serial-port
      - network

parts:
  influx-setup:
    plugin: dump
    source: influx/
    prime:
      - conf/default-influxdb.conf
      - bin/influxd.wrapper
  influxdb:
    plugin: dump
    source: https://dl.influxdata.com/influxdb/releases/influxdb-1.2.0_linux_armhf.tar.gz
  python-import:
    plugin: python
    python-packages:
       - pyserial
       - influxdb
       - zeroconf
  python-daemon:
    plugin: dump
    source: connector/
    prime:
      - bin/db-writer.wrapper
      - bin/data-export.wrapper
      - bin/data-exportd.wrapper
      - piment/db_writer.py
      - piment/data_exporter.py
      - piment/pm_reader.py
      - piment/piment.ini
    organize:
      db_writer.py: piment/db_writer.py
      pm_reader.py: piment/pm_reader.py
      piment.ini: piment/piment.ini
      data_exporter.py: piment/data_exporter.py
