name: pmsensor
version: 0.0.1
architectures: [armhf]
summary: reads stuff
description: |
  writes stuff
grade: devel
confinement: devmode

apps:
  influxd:
    command: bin/influxd.wrapper
    daemon: simple
    plugs:
      - network-bind
  data-export:
    command: bin/data-exporter.wrapper
    daemon: simple
    plugs:
      - network
  writer:
    command: bin/dbwriter.wrapper
    daemon: simple
    plugs:
      - serial-port
      - network

parts:
  influx-setup:
    plugin: dump
    source: influx/
    prime:
      - conf/default-influxdb.conf
      - bin/influxd.wrapper
      - bin/export_data
  influxdb:
    plugin: dump
    source: https://dl.influxdata.com/influxdb/releases/influxdb-1.2.0_linux_armhf.tar.gz
  python-import:
    plugin: python
    python-packages:
       - pyserial
       - influxdb
       - zeroconf
  python-daemon:
    plugin: dump
    source: connector/
    prime:
      - pm/dbwriter.py
      - pm/data_exporter.py
      - bin/dbwriter.wrapper
      - bin/data-exporter.wrapper
      - pm/pmreader.py
      - pm/pmsensor.ini
    organize:
      dbwriter.py: pm/dbwriter.py
      pmreader.py: pm/pmreader.py
      pmsensor.ini: pm/pmsensor.ini
      data_exporter.py: pm/data_exporter.py
