version: '2'
services:
  sensor:
    build: .
    volumes:
     - "pmsensor.ini:/opt/pmsensor/pmsensor.ini"
    links:
     - influxdb
    devices:
     - "/dev/ttyUSB0:/dev/ttyUSB0"
  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
